### ISSUE TITLE
Tried to run the first demo.

### ISSUE THREAD

**Issue by ccristian** [PacktPublishing/Practical-Microservices#2]
Tried to run the mvn install and i got this 
package junit.framework does not exist

**Comment by ccristian** [comment]
It seems it is missing <dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>

As probalby your spring sts provides that by default

**Comment by sohamapackt** [comment]
Hi,

I am closing this issue.
If the problem still persists, feel free to reopen it.

Thanks!
