### ISSUE TITLE
cannot find EnableEurekaServer annotation  

### ISSUE THREAD

**Issue by farhadh121** [PacktPublishing/Practical-Microservices#3]
Hi I just noticed that EnableEurekaServer  annotation would not work unless I add the following dependency:
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
 </dependency>

**Comment by sonam-packt** [comment]
Please reopen if the issue still persists.

**Comment by farhadh121** [comment]
> Please reopen if the issue still persists.

It's our 3 years anniversary. Thank you 🍰
